- src/connection.cpp
- src/pool.cpp
32-bit build errors like this:
cpp-driver/src/connection.cpp: In member function ‘void cass::Connection::consume(char*, size_t)’:
cpp-driver/src/connection.cpp:301: error: format ‘%lu’ expects type ‘long unsigned int’, but argument 7 has type ‘size_t’
I've fixed by casting to int, failing to find a more portable solution.
> Clean-compile on 32-bit architectures

- src/serialization.hpp
We hit this problem compiling on Ubuntu 10.04 with g++ 4.4.
This is a better solution to avoid the strict aliasing warnings when casting
a float/double to an integer.  Strangely, older versions of gcc are better at
reporting a warning in this situation than more recent versions.
The previous copy_cast solution to the alias problem doesn't really solve the problem.  The
code is still accessing a float variable through an integer pointer.  The memcpy of the pointer
inside the copy_cast is enough to stop the compiler tracking that it is an alias, but interestingly
on 4.4 the compiler does track it - hence the warning.
This change uses memcpy() to copy the value, so the same memory location is never aliased.
I compiled the code and as far as I could see from the assembler output the generated …
> Use memcpy to avoid strict aliasing warnings with gcc 4.4

- CMakeLists.txt
When including the cmake file from a parent cmake project, Boost_FOUND may
be set even though we don't want to use an external boost (for example,
because the version of boost is not new enough to support the test code)
Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>
> Test correct flag for using external boost

- src/loop_thread.hpp
The assert() macro expands to do nothing in a release build, so any side
effects of the expression being asserted do not occur.
This was causing random crashes and memory corruptions in a release-mode build
of the driver.
Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>
> join() call is not happening in release builds

- src/random.cpp
FreeBSD needs the same STRERROR_R definition used for OS X.
> Pick the correct STRERROR_R macro for FreeBSD

- packaging/homebrew/cassandra-cpp-driver.rb
Just a quick update to the homebrew formula to reflect the new driver version. I tested it here:
brew install https://raw.githubusercontent.com/pmcfadin/cpp-driver/master/packaging/homebrew/cassandra-cpp-driver.rb
Works great.
> Update homebrew formula to use version 2.0

- CMakeLists.txt
Clang 3.6 warns about unused local typedefs and causes a compilation error to occur because of -Wall.
See build log at
http://beefy4.nyi.freebsd.org/data/head-amd64-default/p390348_s284712/logs/cassandra-cpp-driver-2.0.1.log
> Support building with Clang 3.6

- test/integration_tests/src/test_outage.cpp
- test/integration_tests/src/test_pool.cpp
Removed old code and comment from outage test (fixed in CPP-140)
> CPP-253 Ensure entire pool is not removed with partial connections

- topics/README.md
- topics/basics/batches/README.md
- topics/basics/binding_parameters/README.md
- topics/basics/keyspaces/README.md
- topics/basics/prepared_statements/README.md
- topics/security/ssl/README.md
This function and the corresponding CassString wrapper type were removed
in version 2.0.
> docs: remove cass_string_init from all code samples

- src/mpmc_queue.hpp
The intrinsics implementation already emits a memory fence in the final
store to the sequence in MPMC so it doesn’t require the extra fence.
> 269 - MPMC queue should emit a memory fence on x86/x64

- CMakeLists.txt
Makes it possible to use Ninja as the build tool.
Note that this is not tested on Windows, but *should* work. If it doesn't let me know and I'll add the check back and rebase.
> Reworking how LOG_FILE_ is computed in a more CMake idiomatic way

- src/third_party/hdr_histogram/hdr_histogram.cpp
The LZCNT instruction produced by __lzcnt on Windows is not available
on many CPUs in use today. BSR is a safe replacement requiring only
minimal additional work.
> Replace LZCNT with BSR instruction in hdr_histogram

- src/cluster.cpp
It will automatically be negotiated to a valid value using the control
connection and it's one more place in the code that needs to be updated.
> 318 - Removed upper bound protocol validation

- topics/building/README.md
Only documentation updates are required after d68233f is merged from #233
> 316 - Build Fails on OS X El Capitan

- .travis.yml
- test/integration_tests/src/main.cpp
PPA version of Boost has also been removed and v1.59.0 is now being built from source (only the required libraries for test). This along with libuv are cached between builds so the first build will be the most expensive build. Once this is merged with master, new branches should utilize the master cache and not require the building of Boost; unless boost version is upgraded in .travis.yml.
NOTE: This PR should be manually merged in order to remove 75d32f7 from being merged in; preventing conflicts. This fix already exists in #231 [here](https://github.com/datastax/cpp-driver/commit/ffe86049ef8db7e140aa6a7eba2c95c48262399a#diff-b652c53f944ec1f4f07664a16d1ee025R53)
> 319 - Upgrade TravisCI to use container-based infrastructure

- include/cassandra.h
Some documented values in cassandra.h didn't match the actual values
in config.hpp.
The pending requests high water mark referred to max_connections_per_host
suggesting it is calculated from that value. This is not the case, it will
always be 128 * 2.
> Fix documentation of default values

- src/atomic/atomic_intrinsics_msvc.hpp
- test/unit_tests/src/test_metrics.cpp
Also addressed threshold issues for 32-bit slowness of metrics
> 329 - Atomic [MSVC Intrinsics] fails to compile; 32-bit only

- test/ccm_bridge/src/bridge.cpp
In contrast to the other functions _read is declared in io.h.
> Fix compile error in CCMBridge on Windows

- examples/callbacks/callbacks.c
- Don't connect_keyspace (in case it's not there)
- Fix exit handling for failed session connect
> Fix callback example

- examples/callbacks/callbacks.c
- src/connection.cpp
- src/connection.hpp
- src/io_worker.cpp
- src/io_worker.hpp
- src/pool.cpp
- src/pool.hpp
- src/session.cpp
- src/session.hpp
- src/set_keyspace_handler.cpp
- src/string_ref.hpp
- test/integration_tests/src/test_sessions.cpp
- test/unit_tests/src/test_string_ref.cpp
Also, 690c7d0 fixes a bottleneck I found when benchmarking.
> 281 - Handle error when connecting with keyspace that doesn't exist

- include/cassandra.h
- topics/configuration/README.md
Added documentation for new datacenter filtering policies
> 340 - Updating documentation for filtering policies

- src/control_connection.cpp
Adding a connection pool as a result of an event before the driver is
done with its connection process causes the pending pool count to never
decrement to zero. Events are no longer able to add or remove pools
until the control connection ready.
> 367 - Fix: Session connect hangs because of "UP" event

- src/metadata.cpp
- src/value.cpp
- Adding a data type to "null" values (commit:
bf2d53f3542fcdbb41d9cff113b8c56d9931cd10) changed an assumption about
how a "null" (or valid) values could be determined.
> Fix: Adding valid data type to null values caused segfault in metadata

- src/future.cpp
When attempting to get future error result from future without response, got the following stack trace:
```
#0  0x00007ffff10d5f7d in boost::atomics::detail::base_atomic<int, int, 4u, true>::fetch_add (this=0x8, v=1, order=boost::memory_order_relaxed)
at include/boost/atomic/detail/gcc-x86.hpp:612
#1  0x00007ffff10d48d8 in cass::Atomic<int>::fetch_add (this=0x8, value=1, order=cass::MEMORY_ORDER_RELAXED)
at cpp-driver/src/atomic/atomic_boost.hpp:48
#2  0x00007ffff10dd236 in cass::RefCounted<cass::Response>::inc_ref (this=0x8) at cpp-driver/src/ref_counted.hpp:42
#3  0x00007ffff114fcda in cass_future_get_error_result (future=0x7fff780017c0) at cpp-driver/src/future.cpp:101
#4  0x00007ffff6f7b179 in cassutils::buildErrorFromFuture (pFuture=0x7fff780017c0, errorOut="Invalid query") at 
```
> Avoid core while extracting error message from future w/NULL response.

- examples/async/async.c
- examples/auth/auth.c
- examples/basic/basic.c
- examples/batch/batch.c
- examples/bind_by_name/bind_by_name.c
- examples/callbacks/callbacks.c
- examples/collections/collections.c
- examples/date_time/data_time.c
- examples/logging/logging.c
- examples/maps/maps.c
- examples/named_parameters/named_parameters.c
- examples/paging/paging.c
- examples/perf/perf.c
- examples/prepared/prepared.c
- examples/schema_meta/schema_meta.c
- examples/simple/simple.c
- examples/ssl/ssl.c
- examples/tuple/tuple.c
- examples/udt/udt.c
- examples/uuids/uuids.c
- test/ccm_bridge/data/config.txt
- test/ccm_bridge/src/bridge.cpp
- test/ccm_bridge/src/bridge.hpp
- Sometimes branch/tags do not conform to `cassandra-<version_number>` and when requesting git versions the ability to force an exact branch/tag was not available; this corrects that issue.
- Driver example contact points are no longer hardcoded `127.0.0.1`, can be specified via command line
> CCM branch/tag specification and host argument for examples

- src/resolver.hpp
- src/session.cpp
Resolve multiple addresses for each domain name. Before only one IP was returned even if the domain name resolves to several IP addresses. This is useful if a domain name resolves to all the the client seednodes.
The code is tested but no test is included since it would rely on a nameserver which cannot be _simply_ and reliably provided to an integration test.
> Resolve multiple addresses for each domain name.

- cmake/modules/CppDriver.cmake
This avoids including a header from a previously installed version of
cpp-driver.
> Make sure our in-source include directories come first.

- test/integration_tests/src/test_schema_metadata.cpp
The comment of the test states this test is meant for Cassandra 2.2+ yet the check makes it run against version 2.1 as well.
> Fix version check in schema_metadata/lookup test

- src/uuids.cpp
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>
> Fix problems compiling on power8 due to char defaulting to unsigned

- CMakeLists.txt
In the case that the cpp-driver is built as a transitively linked library
(aka embedded in another CMake project), the module path will be augmented
relative to the project root instead of this project.
> Ensure that the CMAKE_MODULE_PATH is set correctly even if this project is transitively linked

- docs.yaml
- topics/testing/README.md
- topics/testing/running/README.md
* Update docs.yaml to exclude an appveyor url from external link checking. The link is good, but documentor erroneously thinks the link is bad.
> Document how to run unit and integration tests

- src/session.cpp
Fix for an issue where a session can hang during its connection process
because there are no hosts available in the local DC.
> 398 - Invalid local DC can cause connect hang

- src/metrics.hpp
Histogram metrics were incorrectly counting the same values repeatedly.
> CPP-433 - Request metrics returning zero percentiles

- topics/basics/handling_results/README.md
The snippet uses 'future', when it should use 'query_future'.
> Use correct variable name in an example of paging results

- src/utils.hpp
The _BitScanReverse functions now require intrin.h to be included.
> Add missing include for MSVC15

- packaging/homebrew/cassandra-cpp-driver.rb
I know about the same pull request, #328, but it has not been merged yet.
I updated the formula for cpp-driver 2.7.0 on MacOSX 10.12, and 
I could install this formula without boost160 using brew tap normally.
Please check it :-)
> Updated for cpp-driver 2.7.0 on MacOSX 10.12.

- .travis.yml
- include/cassandra.h
- src/error_response.cpp
* Removed `cass_cluster_set_queue_size_log` from API header
* Corrected API methods
* `cass_error_result_actual` => `cass_error_result_responses_required`
* `cass_error_result_required` => `cass_error_result_responses_required`
* TravisCI updates
* Added a exported symbol check to TravisCI
* Updating docker instance to use Ubuntu 14.04 (Trusty Tahr)
* Adding `--no-check-certificate` for downloads (https redirects)
* Removing Boost atomic usage
* Moving processor count to environment variable
> CPP-473/CPP-502: Correcting exported symbols

- src/murmur3.cpp
- src/third_party/rapidjson/patches/remove_implicit-fallthrough_warnings.diff
- src/third_party/rapidjson/rapidjson/reader.h
Tested with GCC v7.1.1-3 on Fedora 26
> CPP-486: Handle compiler warning `implicit-fallthrough` on C++17 compilers

- src/io_worker.cpp
- src/io_worker.hpp
- src/pool.cpp
- src/session.cpp
- src/session.hpp
The keyspace state in session is attempting to use CopyOnWritePtr as a
mechanism to prevent locking however it just ends up using it as a share
pointer swap which is not atomic. This is a data race and could cause a
memory leak (or freed memory access).
> CPP-513 - Copy-on-write keyspace logic is incorrect

- cmake/modules/FindOpenSSL.cmake
- docs.yaml
- topics/building/README.md
Cherry picked [449c457](https://github.com/riptano/cpp-dse-driver/commit/449c457948ab720c2d4b9f31a7532604f17ecc93) to correct build issues on Mac OS and keep the documentation generic.
> CPP-516: Update build documentation

- src/metadata.cpp
- src/metadata.hpp
- test/integration_tests/src/test_schema_metadata.cpp
* During a drop view event where multiple views exist for a table,
the view(s) remaining in the TableMetadata were not properly
updated with the new base table; ViewMetadata::base_table_.
**NOTE**: This PR is set to merge with CPP-534
> CPP-535: Schema metadata views not being properly updated

- include/cassandra.h
- src/cluster.cpp
https://datastax-oss.atlassian.net/browse/CPP-325
- add api `cass_request_set_default_consistency`, ` cass_request_get_default_consistency` 
- initial default value is `CASS_CONSISTENCY_LOCAL_ONE` (unchanged)
> CPP325: Add the ability to set the default consistency level for statements

- gtests/src/integration/integration.cpp
- gtests/src/integration/integration.hpp
- gtests/src/integration/objects/cluster.hpp
- gtests/src/integration/options.cpp
- gtests/src/integration/tests/test_basics.cpp
- gtests/src/integration/tests/test_null_string_params.cpp
- include/cassandra.h
- src/cluster.cpp
- src/config.hpp
- src/connection.cpp
- src/startup_request.cpp
- src/startup_request.hpp
- test/ccm_bridge/src/bridge.hpp
- test/ccm_bridge/src/cass_version.hpp
Starting with Apache Cassandra v4.0, Thrift and COMPACT STORAGE is no
longer supported. For uninterrupted cluster upgrades, the C/C++ driver
supports the 'NO_COMPACT' startup option. Enabling this feature using
cass_cluster_set_no_compact() will have same effect as
'DROP COMPACT STORAGE', but only for the connected session.
> CPP-578 - Add support for `NO_COMPACT` startup option

- cmake/modules/CppDriver.cmake
An error message will be presented during the CMake configuration
process if integration tests are being built and the provided Boost
version is v1.66.0+ and the CMake version is not v3.11.0+.
> CPP-584 - win: Produce error message if using Boost v1.66.0+

- gtests/src/integration/objects/cluster.hpp
- gtests/src/integration/tests/test_control_connection.cpp
- include/cassandra.h
- src/cluster.cpp
- src/config.hpp
- src/connection.cpp
Fix https://datastax-oss.atlassian.net/browse/CPP-499, i.e., add `cass_cluster_set_local_address` to allow clients to bind a local IP address before connecting to Cassandra. This is important for hosts using multiple network interfaces with strict network separation requirements.
> CPP-499 allow local bind

- packaging/build_deb.sh
dch utility is placed in devscripts package, not in debhelper
> Fixed dch utility package name

- gtests/src/unit/mockssandra.cpp
- gtests/src/unit/mockssandra.hpp
- gtests/src/unit/tests/test_cluster.cpp
- src/cluster.cpp
- src/cluster.hpp
- src/cluster_connector.cpp
- src/dc_aware_policy.hpp
- src/session_base.cpp
The DC-aware load balancing policy depends on an internal host map to determine host distance. The problem was the host distance was being checked to determine whether a node should be added or marked as up.  This fix always adds and marks hosts up even if they're ignored. The distance is only used to determine if a host should have a connection pool.
> CPP-687 - Fix recovery of remote DC host

- cmake/modules/FindLibuv.cmake
Hi,
I try to build the project on Ubuntu 16.04
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```
I have installed libuv
```
ii  libuv1:amd64                     1.8.0-1                               amd64        asynchronous event notification library - runtime library
ii  libuv1-dev:amd64                 1.8.0-1                               amd64        asynchronous event notification library - development files
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libuv1-dev
/usr/share/doc/libuv1-dev/copyright
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libuv.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libuv.pc
/usr/include
/usr/include/uv-errno.h
/usr/include/uv-version.h …
```
> Fixed libuv library searching

- examples/udt/udt.c
- src/control_connector.cpp
A typo in `ControlConnection` prevents UDT schema metadata from being
properly updated.
> CPP-755 UDT schema metadata not properly populated/updated

- include/cassandra.h
Somehow this one entry had the `[in]` after the variable names instead of just after `\param`.
> Fixed the location of the '[in]' information for Doxygen.

- packaging/debian/rules
Adds current version for correct transitive dependencies.
Without this patch shlib file doesnt contain minimal compatible version of cassandra-cpp-driver and transitive dependencies may be broken.
> Fix generation of shlib deps file for debian packages 

- src/deque.hpp
- src/map.hpp
- src/vector.hpp
Under GCC9 `-Werror=deprecated-copy` makes an implicit declaration of
a copy constructor an error if a user-provided one exists.
See also: https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/C_002b_002b-Dialect-Options.html#index-Wdeprecated-copy
> CPP-754: remove user-defined copy contructors

- src/random.cpp
This doesn't solve the problem of somehow you allow it to initiate with no contact points rather than noop or graceful error (with php-driver try to connect with host as empty string).
> Allow random to work with 0.

- CMakeLists.txt
- packaging/cassandra_static.pc.in
Add `openssl` to the required library list in pkg_config file when building a static library. Otherwise pkg_config complains if `CASS_USE_OPENSSL` is enabled. Generated .pc file is:
```
prefix=/usr/local
exec_prefix=/usr/local
libdir=/usr/local/lib64
includedir=/usr/local/include/cassandra-datastax
Name: cassandra
Description: A C/C++ client driver for Apache Cassandra
Version: 2.13.0
Requires: libuv openssl
Libs: -L${libdir} -lcassandra_static -lstdc++
Cflags:
URL: https://github.com/datastax/cpp-driver/
```
> Add openssl to the required library list in pkg_config file

- src/ssl/ssl_no_impl.hpp
A silly trivial mistake that somehow made it into the latest release
> The Current Release Doesn't Compile with CASS_USE_OPENSSL off

- CHANGELOG.md
- src/request_processor.cpp
When a host comes back up after being down, a request processor (unlike a control connection) only notifies the load balancing policy if the host is not ignored.
Sadly some policies ignore remote hosts that are down.
In combination, this means that remote hosts can never be used by a request (processor) after having once gone down.
This fix resolves this, by always notifying a policy of all host-up events, regardless of the distance of that host.
I've tested this locally, and it has the desired effect. My test case is:
* Start nodes in two datacenters. 
* Set up a token-aware, dc-aware policy.
* Take down the local DC. Observe traffic still goes to the remote DC.
* Take down the remote DC. Observe traffic fails (as expected).
* Bring up the remote DC. Expect traffic will start going to …
> CPP-879 Allow remote hosts to come back up

- packaging/cassandra.pc.in
- packaging/cassandra_static.pc.in
With this patch
```
$ pkg-config cassandra -cflags
-I/usr/include/cassandra 
```
> fix cflags when build with CASS_INSTALL_HEADER_IN_SUBDIR on

- src/request_processor_initializer.cpp
- src/request_processor_initializer.hpp
Three `i`s just are not good enough to initialize properly ;)
> Fix typo in RequestProcessorInitializer::internal_initialize

- src/CMakeLists.txt
Since 90a61971299259a8d1e8de7311936b28606ea56b#diff-af3b638bc2a3e6c650974192a53c7291  `PROJECT_NAME_STRING` is no more defined
> fix CASS_INSTALL_HEADER_IN_SUBDIR usage

- src/ssl/ssl_openssl_impl.cpp
Despite what the documentation[1] says the code is not fully compatible
with OpenSSL 1.1 because it relies on compatibility wrappers behind
OPENSSL_API_COMPAT.
The OpenSSL documentation on library initialization[2] explains that
none of the startup fucntions are necessary starting with 1.1. The
changelog for "changes between 1.0.2h and 1.1.0 [25 Aug 2016]"[3]
mentions several removed shutdown functions. The removal of
`CRYPTO_set_locking_callback` is mentioned in a GitHub comment[4].
[1] https://docs.datastax.com/en/developer/cpp-driver/2.15/topics/building/
[2] https://wiki.openssl.org/index.php/Library_Initialization
[3] https://www.openssl.org/news/changelog.html
[4] https://github.com/openssl/openssl/issues/1260#issuecomment-228846202
> Reach full compatibility with OpenSSL 1.1

- src/statement.cpp
Honor the value_length parameter when binding strings by
name in cass_statement_bind_string_by_name so that it can
work properly with non null-terminated strings.
> Honor the value_length param

- src/connection.cpp
- src/request_callback.cpp
- src/request_callback.hpp
Bad data could catch an existing stream in an invalid request state.
It's not the best choice to have an assertion triggered by bad data from
the server-side.
> Defunct connection instead of using assertion

- src/callback.hpp
- src/cluster.cpp
Created a smart pointer owning version of `Callback` to ensure that `Cluster` lives as long as `PrepareHostHandler`.
> CPP-924 Pure virtual function called when Session object is being destructed

- src/resolver.hpp
- src/socket_connector.cpp
`SocketConnector::resolved_address_offset_` is never incremented because
the first parameter was wrong. Also, this adds a default filter for
resolver hints to prevent duplicates in the resolved IPs.
> Fix: Only using a single resolved IP when connecting with hostname

- src/http_client.cpp
The `Host:` header was being set to the resolved IP address (and port)
instead of the hostname.
> Fix `Host:` header when calling metadata service

- src/CMakeLists.txt
Newer clang versions report several "Wimplicit-int-float-conversion"
warnings. In this commit, implicit int-to-float conversions are turned
into explicit static_casts in local code; violations in third-party
headers are suppressed by compiler pragma.
> Fix build with clang-{10,11}

- src/atomic.hpp
- src/ref_counted.hpp
Thread sanitizer does not support `atomic_thread_fence` with release/acquire order, so using of `atomic_thread_fence(MEMORY_ORDER_ACQUIRE)` in `RefCounted::dec_ref()` causes false positive reports like this: https://gist.github.com/alesapin/96b14caa274a291f12dcf84cddc8ff5c
Explicit annotation avoids such false positives.
> Add tsan annotation for atomic_thread_fence

- src/third_party/http-parser/http_parser.c
Using other libraries having the same http_parser shows linker error.
> multiple definition of `http_message_needs_eof'
> Avoid potential linker error for http_message_needs_eof

- packaging/debian/control
As of Ubuntu Focal Fossa (20.04) the transitional `multiarch-support` package (introduced in Natty Narwhal) has _finally_ been removed.  This MR removes the explicit dependency on that package which unblocks adding a Focal Fossa build of the library.
The details of the change required quite a bit of research so I've written up my findings and logic here:
Back in 2006 glibc added a model for separating 32bit/64bit libraries between separate library paths (`/usr/lib/x86_64-linux-gnu` vs `/usr/lib/i386-linux-gnu`).  Debian (and thus Ubuntu) adopted that policy into their package manager around the time of the Natty Narwhal release, but any packages that used the new paths needed a version of `ld-linux.so` that knew to look in the architecture-specific paths for dynamic libraries.  To make …
> Swap multiarch-support for a defensive dependency on libc6

- src/latency_aware_policy.cpp
- src/request_processor.cpp
- tests/src/integration/tests/test_latency_aware_policy.cpp
Latency-aware policy update timer wasn't started on request processors.
> CPP-935: Fix latency-aware policy

- src/collection_iterator.cpp
- src/decoder.cpp
- src/decoder.hpp
- src/map_iterator.cpp
- src/row.cpp
- src/user_type_field_iterator.cpp
- src/value.hpp
Please consider this optimisation, it gives about 39% improvement in **decode_value**, this results in 2-3% improvement in our production backend, which is considerable taking in account the scale of our deployments.
**decode_value** 7.55%, on the right side **Value::operator=** & **Value::~Value**
**decode_value** 4.67%
> Performance improvement in Decoder::decode_value

- src/collection_iterator.cpp
- src/ref_counted.hpp
- src/user_type_field_iterator.hpp
- src/value.cpp
When profiling our application, we noticed  the cpp-driver spends a lot of time in `Decoder::decode_value` method and its callers, and the most hot instructions were connected to `SharedRefPtr<DataType>::inc_ref` and `::dec_ref` methods, i.e. reference counting. Our application mostly reads rows with large collections of UDTs.
This PR avoids SharedRefPtr's copies on several places on the hot path. Note that on some of the places the optimisation relies on move-semantics; as that is available from C++11, the relevant C++11-only code is hidden behind a feature check macro respecting that the codebase targets also older standards.
I've constructed small benchmark which roughly simulates our workload and hence has similar performance profile. The resulting numbers on my machine (WSL, clang10, …
> optimize iteration through collections and UDTs

- src/decoder.cpp
After the previous perf fix PR, I think udt and tuple values might be broken as they need to be constructed using the specific ctor.
> Fix UDT Value hitting the correct ctor

- src/decoder.cpp
- src/decoder.hpp
- src/result_iterator.hpp
- src/row.cpp
- src/row.hpp
- src/value.cpp
- src/value.hpp
This is a "better" row values decoding optimisation compared to the first attempt https://github.com/datastax/cpp-driver/pull/508
It skips creating **Value** objects and populating the row vector on every next row decode, instead it simply updates **Value's** **Decoder** instance and **Value** internal state.
So there is no refcounting, no vector cleanup and memory allocations.
**cass::ResultIterator::next()** - 13.28%
**cass::ResultIterator::next()** - 4.45%
> Row values decoding performance optimisation

- tests/src/unit/tests/test_decoder.cpp
- tests/src/unit/tests/test_serialization.cpp
- tests/src/unit/tests/test_value.cpp
The signed-ness of 'char' varies by platform. Fix tests that are constructing binary input data as 'char' arrays with negative literals by switching them over to 'signed char' arrays.
https://datastax-oss.atlassian.net/browse/CPP-944
> CPP-944: Fix test builds on aarch64

- src/value.cpp
- tests/src/unit/tests/test_value.cpp
`is_null_` was not correctly updated for the non null values on the next row read, added untittest that simulates the scenario
Also removed `else` branch in the `ctor` that was setting `count_` to zero, it is already set in ctor member initialiser list.
> Non null values wont be read after a row with null value for the column

- src/address_factory.cpp
- src/address_factory.hpp
- src/cluster.cpp
- src/control_connection.cpp
- src/host.cpp
- src/request_processor.cpp
- src/wkt.cpp
When using SNI routing the driver is not mapping event address to the representation used by the driver (an `Address` with an IP and SNI name). It needs to be mapped using the `rpc_address` from the system tables.
> Fix SNI events

- src/ssl/ssl_openssl_impl.cpp
ERR_get_error_line_data is deprecated in OpenSSL >= 3.0.
It can be replaced by the newer function ERR_get_error_all added in OpenSSL 3.0.
> Replace deprecated function for OpenSSL >= 3.0

- include/cassandra.h
- topics/security/ssl/README.md
Add documentation that MITM is possible when using
`CASS_SSL_VERIFY_PEER_IDENTITY_DNS` with
`cass_cluster_set_use_hostname_resolution()`
> Deprecate `cass_cluster_set_use_hostname_resolution()`

- src/ssl/ssl_openssl_impl.cpp
Previously the code which loaded a trusted certificate from file only assumed that there was a single certificate in that file, meaning that using a certificate bundle for certificate verification would not work.
This fix allows the driver to read multiple trusted certificates out of a BIO and provision them in the trusted certificate store.
_This code was already reviewed in #493 but that PR contained other fixes as well and has not yet been merged. Instead, this PR pulls that out separately. It is also now based on master (2.16.2)._
> Iterate over all certificates in a trusted cert BIO, not just the first

- src/ssl/ssl_openssl_impl.cpp
- tests/src/integration/ssl_certificates.hpp
- tests/src/integration/tests/test_ssl.cpp
Follow-up to [PR 522](https://github.com/datastax/cpp-driver/pull/522).  Fix the formatting issue that was breaking the Jenkins build for Ubuntu Bionic and add an integration test to validate the change.
> PR 522 followup

- src/ssl/ssl_openssl_impl.cpp
I'm not totally positive I picked the right version number.
> Fix with newer LibreSSL

- include/cassandra.h
- src/ssl.cpp
- src/ssl.hpp
- src/ssl/ssl_no_impl.cpp
- src/ssl/ssl_no_impl.hpp
- src/ssl/ssl_openssl_impl.cpp
- src/ssl/ssl_openssl_impl.hpp
- tests/src/unit/mockssandra.cpp
- tests/src/unit/mockssandra.hpp
- tests/src/unit/tests/test_socket.cpp
This change allows users of the driver to request that the TLS version is at least a specified minimum. This helps to avoid [downgrade attacks](https://www.praetorian.com/blog/man-in-the-middle-tls-ssl-protocol-downgrade-attack/), such as [POODLE](https://en.wikipedia.org/wiki/POODLE).
In practice I'll always be wanting to call this to enforce TLS1.2, but I thought it made sense to make it optional, and to allow users to say which TLS version they care about so that the driver remains fully back-compatible and flexible.
> Allow users to request TLS client-side enforcement

- tests/src/integration/ssl_certificates.hpp
Details can be found on [CPP-965](https://datastax-oss.atlassian.net/browse/CPP-965)
[CPP-965]: https://datastax-oss.atlassian.net/browse/CPP-965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CPP-965 Use existing invalid cert for multi-cert PEM

- tests/src/integration/ccm/bridge.cpp
- tests/src/integration/integration.cpp
- tests/src/integration/integration.hpp
- tests/src/integration/objects/cluster.hpp
- tests/src/integration/options.cpp
- tests/src/integration/options.hpp
- tests/src/integration/tests/test_auth.cpp
- tests/src/integration/tests/test_dse_auth.cpp
- tests/src/integration/tests/test_exec_profile.cpp
- tests/src/integration/tests/test_prepared_metadata.cpp
- tests/src/integration/tests/test_set_keyspace.cpp
Along with some other miscellaneous fixes as well:
* Remove beta protocol support from the CLI options to the integration test as well as the test cluster itself
* Clean up some error messages
> CPP-966 Compilation warnings after cass_set_use_hostname_resolution() marked as deprecated

- cmake/FindOpenSSL.cmake
This commit reorders the locations where CMake will look for openssl, starting with ${OPENSSL_ROOT_DIR} and then proceeding to system install locations.
This allows the user to provide a different Openssl version with -DOPENSSL_ROOT_DIR=<path/to/openssl>
> Prioritize ${OPENSSL_ROOT_DIR} over system paths

- src/string_ref.cpp
- src/utils.cpp
This fixes the following warnings from MSVC:
warning C4245: 'initializing': conversion from 'int' to 'datastax::StringRef::size_type', signed/unsigned mismatch
warning C4245: '=': conversion from 'int' to 'DWORD', signed/unsigned mismatch
> Fix signed/unsigned mismatch

- src/atomic/atomic_std.hpp
When compiling the code with C++ 20 the following error message is produced:
enumerator value for ‘MEMORY_ORDER_RELAXED’ must have integral or unscoped enumeration type
This is because with C++ 20 the type of those values changed to an enum class. The `static_cast` extracts the numeric values so they can be used here as before.
> Adapt MemoryOrder definition for C++ 20

- Jenkinsfile
A recent rebuild of the Jenkins runners upgraded our Rocky8 runner from 8.8 to 8.9.  This apparently brought with it a new version of cmake which fails to build with the following error:
```
[2024-04-17T17:09:55.769Z] cmake: symbol lookup error: cmake: undefined symbol: uv_fs_get_system_error
```
Function in question is [present](https://docs.libuv.org/en/v1.x/fs.html#c.uv_fs_get_system_error) as of libuv 1.38.0 so my guess is that the new version of cmake leverages functions in the newer libuv that aren't present in the libuv version we were using as a default.
To confirm I ran a test build with LIBUV_VERSION set to 1.38.0 and the build was completely green.
> Update default libuv version to fix Jenkins build

- src/metrics.hpp
Remove C++11 usage in favor of a struct constructor to be explicit about the zero value init
> CPP-999 Compilation error in cpp-driver-2.16.2 when using C++98 standard
