test/integration_tests/src/test_async.cpp, test/integration_tests/src/test_pool.cpp, test/integration_tests/src/test_utils.cpp, test/integration_tests/src/test_utils.hpp
- Adding additional time for timed waits
- Increasing connection throughput
- Updating log message for pool connection test
=> Updating Integration Tests for GA

CMakeLists.txt, test/integration_tests/src/test_sessions.cpp, vc_build.bat
- Allow for header only check using find_package for Boost check (CASS_USE_BOOST_ATOMIC=ON)
- Add ability to use Windows build script to build with Boost atomic and update package building
- Correct sessions/stress integration test
=> Various release fixes in tests and build mainly targeted towards Windows

src/async_queue.hpp, src/mpmc_queue.hpp, src/spsc_queue.hpp
Also submitted libuv PR: https://github.com/libuv/libuv/pull/349
=> CPP-259 - Stopgap fix for hanging issue

src/statement.cpp, test/ccm_bridge/include/cql_ccm_bridge.hpp, test/ccm_bridge/src/cql_ccm_bridge.cpp, test/integration_tests/src/test_async.cpp, test/integration_tests/src/test_basics.cpp, test/integration_tests/src/test_batch.cpp, test/integration_tests/src/test_by_name.cpp, test/integration_tests/src/test_collections.cpp, test/integration_tests/src/test_outage.cpp, test/integration_tests/src/test_paging.cpp, test/integration_tests/src/test_prepared_outage.cpp, test/integration_tests/src/test_schema_agreement.cpp, test/integration_tests/src/test_serial_consistency.cpp, test/integration_tests/src/test_stress.cpp, test/integration_tests/src/test_utils.cpp, test/integration_tests/src/test_utils.hpp, test/integration_tests/src/test_version1.cpp
Backported 2.1.0-beta version of CPP-187 for 2.0 branch.
=> CPP-187 - Enhance Integration Tests for Cassandra v1.2.x (2.0)

src/connection.cpp, src/connection.hpp
Original patch provided by Christian Hägele <haegele@teamviewer.com>
with slight updates to naming and for 2.x compatibility.
=> 247 - Added read buffer caching to connection

.travis.yml, src/connection.cpp, src/connection.hpp
Original patch provided by "Christian Hägele <haegele@teamviewer.com>"
with slight updates to naming/style by "Michael Penick
<michael.penick@datastax.com>".
JIRA: https://datastax-oss.atlassian.net/browse/CPP-247
=> 247 - Added read buffer caching to connection (1.0)

include/cassandra.h, src/result_response.cpp, src/statement.cpp, test/integration_tests/src/test_paging.cpp
- Renamed cass_statement_set_paging_state_raw() to
cass_statement_set_paging_state_token()
=> 254-tests: Added paging state token (raw) integration test

test/doxyfile
Added doxyfile for test documentation
=> Doxyfile test documentation

src/address.cpp
Special thanks to https://github.com/ybainier for finding and providing
the initial fix for the issue.
The original PR: https://github.com/datastax/cpp-driver/pull/234
=> 320 - Fixed IPv4 address comparison

README.md, appveyor.yml, test/unit_tests/src/test_metrics.cpp
NOTE: Increased tolerance for metrics testing on Windows only
=> CPP-343 - AppVeyor Windows CI

src/token_map_impl.hpp, test/unit_tests/src/test_token_map.cpp
* Fixed merging a new host's tokens into a token map
=> CPP-464 - Adding a node breaks token map reconstruction

src/future.cpp
Threads waiting for the results of a future callback might be run before the
callback because the condition variable was signaled before the callback was
run.
=> CPP-514 - Future callback data race

src/buffer.hpp
CPP-438 also relates to CPP-439 which was address in #373
=> CPP-438: Address compiler issues with GCC 7

src/metadata.cpp, src/metadata.hpp, test/ccm_bridge/src/bridge.cpp, test/ccm_bridge/src/cass_version.hpp, test/integration_tests/src/test_schema_metadata.cpp
* CPP-501/CPP-503: Corrupted schema metadata due to existing views 
* Ported fix for CCM cluster naming changes
=> CPP-534: Port CPP-501 and CPP-503

gtests/src/unit/tests/test_string_ref.cpp, include/cassandra.h, src/cluster.cpp, src/config.hpp, src/prepare_host_handler.cpp, src/prepare_host_handler.hpp, src/prepared.hpp, src/request_handler.cpp, src/request_handler.hpp, src/session.cpp, src/session.hpp, src/stream_manager.hpp, src/string_ref.hpp
=> CPP-394 - Prepare statements on UP/ADD events

src/third_party/rapidjson/patches/fix_memaccess.diff, src/third_party/rapidjson/rapidjson/document.h
* This addresses the build issues with GCC 8
=> CPP-674 - Fix memaccess in rapidjson

docs.yaml
Added new YAML option for Swiftype meta element  indexing.
=> DOC-2049: added new option to docs.yaml file.

packaging/cassandra.pc.in, packaging/cassandra_static.pc.in
**Description**
* Changed pkg_config templates to use the library variable name instead of being hard-coded
=> Changed pkg_config templates to use the library variable name

tests/src/unit/tests/test_schema_agreement.cpp
The test stops cluster nodes and then performs queries. It is possible for that query to start being executed before the session detects the connection going down, resulting in test failures.
https://datastax-oss.atlassian.net/browse/CPP-943
=> CPP-943: Fix intermittent failures of SchemaAgreementUnitTest.Simple

Jenkinsfile
And also remove references to Ubuntu Bionic while we're in here.
=> CPP-1001 Remove CentOS 7 as a tested platform
